version: "3.8"

services:
  cratedb:
    image: crate:latest
    container_name: infra_cratedb
    restart: unless-stopped
    ports:
      - "4200:4200"
    volumes:
      - ./cratedb_data:/data
    command: [ "crate", "-Cnode.store.allow_mmap=false" ]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      CRATE_HEAP_SIZE: 2g
    networks:
      - internal
  
  mage-ai:
    image: mageai/mageai:0.9.60
    container_name: "mage_ai_pame"
    command: bash -c "pip install polars-lts-cpu library && /app/run_app.sh"
    ports:
      - "6789:6789"
    volumes:
      - ./mage_projects:/home/src
    environment:
      USER_CODE_PATH: "/home/src/pame_ml_project"
      REQUIRE_USER_AUTHENTICATION: 0
    networks:
      - internal

networks:
  internal:
    name: internal